---
# Run sysbench test
- name: Run sysbench random read RWO test

  block:

    - name:  Run sysbench random read RWO test
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'sysbench_random_read_rwo.yaml.j2') }}"
        wait: yes
        wait_timeout: 7200
        wait_condition:
          type: Complete
          status: "True"

    - name: Get logs of the sysbench random read pod for RWO
      kubernetes.core.k8s_log:
        namespace: "{{ storage_perf_namespace }}"
        label_selectors:
        - job-name=sysbench-random-read-rwo
      register: logo

    - name: Save Log to local file
      local_action:
        module: copy
        content: "{{ logo }}"
        dest: "{{ logfolder }}/random_read_rwo.json"

  rescue:
    - debug:
        msg: 
         - "Run sysbench random read RWO test failed or timed out" 
         - "Please check your openshift storage configuration. This is likely due to poor I/O."
