---
# Run sysbench test
- name:  Setup PVCs to run test on
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'common-objects.yaml.j2') }}"

- name: Wait few seconds for the PVC 
  pause:
    seconds: 60

- name: Create logs directory
  ansible.builtin.file:
    path: '{{ logfolder }}'
    state: directory
    mode: '0755'
